paths:
  milvus_db: 'milvus.db'

models:
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  embed_model_dim: 768

google_genai:
  model: "gemini-1.5-flash-8b-latest"

groq:
  llm: 'llama-3.3-70b-versatile'

chunking:
  chunk_size: 512
  chunk_overlap: 64

retrieval:
  top_k: 5

device:
  type: 'cpu'

web_urls:
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/1166770177/Analytics+Engineering+Workflow+Trial+Server+Beta+Functionality'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/783745025/API'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/1835015/Changelog'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/overview'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/3375116/Ellie+User+Guide+-+the+basics'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/858849281/Feature+deprecation+Reports'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/1217527825/Features+deprecated+with+Ellie+7.0+release'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/2162724/Frequently+Asked+Questions'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/854392835/How+to+create+an+Okta+API+token+for+ellie.ai'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/788103169/How+to+Export+Model+Content+in+JSON+format+using+the+Model+Export+API'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/1835022/How+to+guides'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/1835039/How+to+import+and+export+entities+and+attributes+via+Excel+files'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/867729416/How+to+import+Logical+Models+into+Ellie'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/841613313/Okta+configuration+guide+for+ellie.ai'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/20381697/Privacy+Policy'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/645431297/Software+as+a+Service+Evaluation+Agreement'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/678461441/Terms+of+Service'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/954990595/Terms+of+Service+for+AI+Beta+Features'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/830046209/Using+Custom+Entity+Types+with+Ellie'
  - 'https://ellie.atlassian.net/wiki/spaces/ELLIE/pages/852230147/Working+with+folders+and+glossaries'